# Generated by Django 6.0.3 on 2026-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0017_adminuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='job_type',
            new_name='employment_type',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='qualification',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='application_email',
            field=models.EmailField(blank=True, help_text='Email for receiving applications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='context',
            field=models.TextField(blank=True, help_text='Optional context about the role', null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for the job page', null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='qualifications',
            field=models.JSONField(blank=True, default=list, help_text='List of requirements/qualifications'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='reporting_to',
            field=models.CharField(blank=True, help_text='Who this role reports to', max_length=100),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief summary for card view (max 300 chars)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
